---
id: videoIntroRemix
name: A Video Intro to Remix
summary: Learn how to use the Remix interface.
level: 1
priority: 20
tags:
  - Solidity
  - Remix
  - Video
steps:
  - name: 1. Introduction
    path: 1-intro-tour